// One-shot: take the AI-generated BYUI CAN shield and clear ONLY the outer
// white background (flood-fill from corners). Inner white panels inside the
// shield stay opaque white so the artwork remains readable.
import sharp from "sharp";
import { resolve } from "node:path";

const SRC = process.argv[2] ?? "C:/Users/gabri/Downloads/, AI generated.png";
const OUT = resolve(process.cwd(), "public/byuican-shield.png");

const THRESHOLD = 240; // R, G, and B all above this → "white-ish"

async function main() {
  // Load as raw RGBA so we can mutate per-pixel alpha. ensureAlpha so the
  // RGB-only PNG gets a 4th channel to write into.
  const { data, info } = await sharp(SRC)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const { width: W, height: H } = info;
  const px = Buffer.from(data); // copy so we can mutate

  function idx(x, y) {
    return (y * W + x) * 4;
  }
  function isWhite(i) {
    return px[i] >= THRESHOLD && px[i + 1] >= THRESHOLD && px[i + 2] >= THRESHOLD;
  }

  // BFS from all four image edges. Any white pixel reachable from an edge
  // without crossing a non-white pixel is background.
  const visited = new Uint8Array(W * H);
  const queue = [];
  function push(x, y) {
    if (x < 0 || y < 0 || x >= W || y >= H) return;
    const v = y * W + x;
    if (visited[v]) return;
    const i = idx(x, y);
    if (!isWhite(i)) return;
    visited[v] = 1;
    queue.push(v);
  }

  for (let x = 0; x < W; x++) {
    push(x, 0);
    push(x, H - 1);
  }
  for (let y = 0; y < H; y++) {
    push(0, y);
    push(W - 1, y);
  }

  while (queue.length) {
    const v = queue.pop();
    const x = v % W;
    const y = (v - x) / W;
    const i = v * 4;
    px[i + 3] = 0; // transparent
    push(x + 1, y);
    push(x - 1, y);
    push(x, y + 1);
    push(x, y - 1);
  }

  await sharp(px, { raw: { width: W, height: H, channels: 4 } })
    .png()
    .toFile(OUT);
  console.log("wrote", OUT, `${W}x${H}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
